services:
  mongodb:
    image: 'mongo:latest'
    environment:
      #- 'MONGO_INITDB_DATABASE=db1'
      - 'MONGO_INITDB_DATABASE=test'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27018:27017'
    volumes:
      #- /docker-entrypoint-initdb.d/:src/main/resources/mongodb-init/
      - type: bind
        source: src/main/resources/mongodb-init/
        target: /docker-entrypoint-initdb.d/
        read_only: true
